apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-performance
  labels:
    app: employee-performance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee-performance
  template:
    metadata:
      labels:
        app: employee-performance
    spec:
      containers:
        - name: employee-performance
          image: istiyaqmi9/ems_performance:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081

---


apiVersion: v1
kind: Service
metadata:
  name: employee-performance-service
spec:
  selector:
    app: employee-performance
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: NodePort
