env:
  folder: development-environment

spring:
  config:
    import: optional:configserver:http://localhost:8083

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.101:3306/onlinedatabuilder
    username: istiyak
    password: live@Bottomhalf_001

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8080/eureka

file:
  saver:
    service:
      url: http://localhost:5010/bt/s1/api/

app:
  resourceBaseUrl: "http://localhost:5000/bts/resources/"