server:
  port: 8081

spring:
  profiles:
    active: dev
  application:
    name: employee-performance-service

  cloud:
    kubernetes:
      discovery:
        all-namespaces: true



---
spring:
  config:
    activate:
      on-profile: default
    import: optional:configserver:http://localhost:8083

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.101:3306/onlinedatabuilder
    username: istiyak
    password: live@Bottomhalf_001

---
spring:
  config:
    activate:
      on-profile: dev
    import: optional:configserver:http://configserver-service:8083

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # url: jdbc:mysql://194.233.76.48:3306/onlinedatabuilder
    url: jdbc:mysql://192.168.0.101:3306/onlinedatabuilder
    username: istiyak
    password: live@Bottomhalf_011

---

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  jpa:
    hibernate.ddl-auto: none
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss


management:
  health:
    circuitbreakers:
      enabled: true

  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      countryList:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
