server:
  port: 8081

spring:
  application:
    name: employee-performance-service

  profiles:
    active: default

  cloud:
    kubernetes:
      discovery:
        all-namespaces: true

  config:
#    discovery:
#      enabled: true
#      service-id: config-service
#      port: 8083
    import: optional:configserver:http://configserver-service:8083

#eureka:
#  client:
#    enabled: true
#    serviceUrl:
#      defaultZone: http://localhost:8080/eureka


management:
  health:
    circuitbreakers:
      enabled: true

  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      countryList:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
